#define UXR_STATUS_ERR_INVALID_DATA         0x85
#define UXR_STATUS_ERR_INCOMPATIBLE         0x86
#define UXR_STATUS_ERR_RESOURCES            0x87
#define UXR_STATUS_ERR_AUTHENTICATION       0x88

#define UXR_REQUEST_ID_MAX_SAMPLES          0
#define UXR_REQUEST_ID_SEQUENCE_NUMBER      1 